### ISSUE TITLE
AttributeError: module 'lightautoml' has no attribute '__version__'

### ISSUE THREAD

**Issue by KovalevEvgeny** [sberbank-ai-lab/LightAutoML#3]
After successful run of  `pip install lightautoml`, I tried to see the version of the module:

```
import lightautoml
print(lightautoml.__version__)
```

Unfortunately, I faced the following:
```
AttributeError: module 'lightautoml' has no attribute '__version__'
```

Is it OK? How come I can't see package version...

**Comment by KovalevEvgeny** [comment]
UPD:

There's still a way to check version by doing this:

```
import pkg_resources
pkg_resources.get_distribution('lightautoml').version
```

However, it seems to be a more complex way 😄

**Comment by alexmryzhkov** [comment]
Hi @KovalevEvgeny!

Thanks for the issue. I have fixed that in `bugfix/version_fix` branch. 
Could you please check installation from WHL file I attached here (you need to unzip WHL file because it can't be upload without archive)?
[LightAutoML-0.2.6-py3-none-any.whl.zip](https://github.com/sberbank-ai-lab/LightAutoML/files/5654418/LightAutoML-0.2.6-py3-none-any.whl.zip)

Alex

**Comment by KovalevEvgeny** [comment]
@alexmryzhkov Thank you, I tested, this wheel really helps to show package version)
