### ISSUE TITLE
 AssertionError: Pipeline finished with 0 models for some reason

### ISSUE THREAD

**Issue by darenr** [sberbank-ai-lab/LightAutoML#41]
I might have coded this incorrectly (very likley) but I'm getting the error:

```Pipeline finished with 0 models for some reason. Probably one or more models failed'
AssertionError: Pipeline finished with 0 models for some reason``
```
Reproducible test case:

[nlp.zip](https://github.com/sberbank-ai-lab/LightAutoML/files/6635578/nlp.zip)

lightautoml==0.2.14
huggingface-hub==0.0.8
transformers==4.6.1
python=3.9.5
```

LightAutoML is an amazing project, thank you

**Comment by DESimakov** [comment]
Do you have a GPU? We don't use a NN without the GPU due to low training speed on the CPU.

Your example works on kaggle notebook, but it has another python version.
Link to kaggle kernel https://www.kaggle.com/simakov/notebookf7a1bdef0f

So if you have the GPU, the reason is python. We haven't tested LAMA with python 3.9+.

**Comment by DESimakov** [comment]
One more thing. If you want to specify bert model for the NN, you should do it directly:
```
nn_params={'opt_params': {'lr': 1e-5},
                   'max_length': 128, 'bs': 32, 'epoch': 1,
                   'lang': 'en',
                   'bert_model': 'distilbert-base-uncased'
                   },
```

**Comment by alexmryzhkov** [comment]
@darenr Hi Daren, does the message above fix your issue?

**Comment by darenr** [comment]
yes, thank you
