### ISSUE TITLE
Проблемы с установкой либы

### ISSUE THREAD

**Issue by alexeytomashyov** [sberbank-ai-lab/LightAutoML#5]
При установке на mac и WSL на питон 3.8 ругается при установке opencv.
На mac на питон 3.6 встала, но ругается при импорте
```OSError: dlopen(/Users/tomashev-aa/lightautoml/lama-venv/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/tomashev-aa/lightautoml/lama-venv/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found
```

На WSL на питон 3.6 встала и работает)

**Comment by StrikerRUS** [comment]
@alexmryzhkov Hi!


> На mac на питон 3.6 встала, но ругается при импорте

This package depends on LightGBM. And default LightGBM version which comes from PyPI uses OpenMP library.

For macOS, I'm pretty sure that the root cause is in [absence of OpenMP](https://github.com/microsoft/LightGBM/issues/2972#issuecomment-609068524). You can try to fix it by running `brew install libomp`.

**Comment by alexeytomashyov** [comment]
`brew install libomp` worked for me. Thank you @StrikerRUS.
The issue can be closed.
