### ISSUE TITLE
Save the trained models 

### ISSUE THREAD

**Issue by niyuzheno1** [sberbank-ai-lab/LightAutoML#84]
Hi,

I have a quick question. How do we save the trained lightautoml model? After reading the documentation, it seems to me that there is no way for us to save the model without using things like pickle.

**Comment by alexmryzhkov** [comment]
Hi @niyuzheno1,
To save the model you can use `joblib.dump(automl, ‘model.pkl’)`.
To load the model you can use `automl=joblib.load(‘model.pkl’)`

Both these commands need import joblib at the begging of the script.

**Comment by niyuzheno1** [comment]
I want to save my model whenever a submodel is trained. More specifically, I want to have the functionality that suppose we have models such as `lgb, lgb_tuned, linear_l2, cb`. Whenever one of the models get trained, we will save the current version of the model.

**Comment by AlexanderLavelle** [comment]
@niyuzheno1 I wonder if this article might further your cause? [AnalyticsIndiaMag - Custom Pipeline](https://analyticsindiamag.com/hands-on-python-guide-to-lama-an-automatic-ml-model-creation-framework/)

**Comment by alexmryzhkov** [comment]
@niyuzheno1 we have investigate different ideas about saving the models separately, but it's just not possible because LightAutoML is not just the models - it's the full pipeline from the raw data to the predictions and even further. That's why we save the whole pipeline at the end and use it for the prediction.
