### ISSUE TITLE
AutoML benchmark - where I can find results

### ISSUE THREAD

**Issue by mglowacki100** [sberbank-ai-lab/LightAutoML#9]
Hi
I've just watched https://vimeo.com/485383651 - great work.
There is the link to https://github.com/sberbank-ai-lab/automlbenchmark, I've looked at couple of scripts and different branches but I can't find results like charts from presentation. 
Is it necessarry to run benchmarks by yourselft or I didn't noticed it. It'd be great to have link to results/comparison directly in documentation or main git page.

**Comment by dev-rinchin** [comment]
Hi @mglowacki100 !

This video presented the results of a dev version of the library, but since then we have made a release with our latest version, and we are calculating the benchmark with our newest version right now, the results will be presented in https://github.com/sberbank-ai-lab/automlbenchmark soon, I will notify you about that in this issue.

Thank you!

**Comment by dev-rinchin** [comment]
@mglowacki100 sorry for the late reply. You can find it here:
https://github.com/sberbank-ai-lab/automlbenchmark/tree/lightautoml

**Comment by mglowacki100** [comment]
Thanks !
